# Generated by Django 4.1 on 2022-09-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport_feedbacks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airport_name", models.CharField(max_length=500)),
                ("link", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=500)),
                ("author_country", models.CharField(max_length=500)),
                ("date", models.DateField()),
                ("content", models.CharField(max_length=10000)),
                ("overall_rating", models.CharField(max_length=500)),
                ("queuing_rating", models.CharField(max_length=500)),
                ("terminal_cleanliness_rating", models.CharField(max_length=500)),
                ("airport_shopping_rating", models.CharField(max_length=500)),
                ("recommended", models.IntegerField()),
            ],
        ),
    ]
