# Generated by Django 3.1 on 2022-12-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport_feedbacks',
            name='airport_staff_rating',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='airport_feedbacks',
            name='food_beverages_rating',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='airport_feedbacks',
            name='terminal_seating_rating',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='airport_feedbacks',
            name='terminal_signs_rating',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='airport_feedbacks',
            name='wifi_connectivity_rating',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='airport_feedbacks',
            name='airport_shopping_rating',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='airport_feedbacks',
            name='author_country',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='airport_feedbacks',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='airport_feedbacks',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='airport_feedbacks',
            name='recommended',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airport_feedbacks',
            name='terminal_cleanliness_rating',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
